server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /healthz {
    proxy_pass http://backend:3001/healthz;
  }

  location /readyz {
    proxy_pass http://backend:3001/readyz;
  }

  location /openapi.stage4a.json {
    proxy_pass http://backend:3001/openapi.stage4a.json;
  }

  location /openapi.stage4b.json {
    proxy_pass http://backend:3001/openapi.stage4b.json;
  }

  location /openapi.stage4c.json {
    proxy_pass http://backend:3001/openapi.stage4c.json;
  }

  location /api/ {
    proxy_pass http://backend:3001/api/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
