-- Stage 5C · production pre-start schema check template.
-- The executable copy is generated by:
-- node scripts/stage5c-production-migration-hardening.mjs schema-sql --output /secure/path/prestart-schema-check.sql
--
-- This checked-in template documents the checks. Run the generated SQL against
-- the operator-owned PostgreSQL database before first clinical use.

do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'app_users'
  ) then
    raise exception 'Stage 5C schema check failed: app_users missing';
  end if;

  if not exists (
    select 1 from pg_trigger where tgname = 'audit_log_no_update'
  ) then
    raise exception 'Stage 5C schema check failed: audit append-only trigger missing';
  end if;

  if exists (
    select 1 from app_users where email = 'doctor.demo@example.invalid'
  ) then
    raise exception 'Stage 5C production seed policy failed: demo auth seed is present';
  end if;

  if not exists (
    select 1 from user_roles where role = 'system_admin'::app_role
  ) then
    raise exception 'Stage 5C bootstrap check failed: no system_admin role found';
  end if;
end $$;
