export function timelineReasonLabel(reason: string): string {
  if (!reason) return "служебная причина скрыта";
  if (reason.includes("not_ready") || reason.includes("requires") || reason.includes("required")) {
    return "требует разбора";
  }
  if (reason.includes("ready")) return "подтверждено";
  if (reason.includes("заблокировано")) return "заблокировано";
  if (reason.includes("approved")) return "утверждено";
  return "служебная причина скрыта";
}

export function humanFieldTerm(term: string): string {
  const labels: Record<string, string> = {
    "2nd review": "Повторный разбор",
    Adjudicated: "Согласовано",
    Adjudication: "Согласование",
    Analysis: "Правила анализа",
    Archive: "Архив",
    Archived: "В архиве",
    Assets: "Снимки",
    Assign: "Назначение",
    Assigned: "Назначено",
    Assessment: "Оценка",
    Blinded: "Закрытая выборка",
    Blocked: "Блок",
    Blockers: "Препятствия",
    Bridge: "Связь устройства",
    "Closed Ex.": "Исключения закрыты",
    Conclusion: "Заключение",
    Consensus: "Согласие",
    "Consensus open": "Согласие открыто",
    Coverage: "Покрытие",
    Dataset: "Данные",
    "Dataset lock": "Данные",
    Delivery: "Выдача",
    Device: "Устройство",
    Disagree: "Разногласия",
    Drift: "Сдвиг",
    "Drift open": "Сдвиг открыт",
    Drills: "Проверки отката",
    Escalated: "Передано",
    Escalation: "Передача",
    Evidence: "Подтверждения",
    Exceptions: "Исключения",
    "Exceptions closed": "Исключения закрыты",
    Export: "Выгрузка",
    "File proxy": "Доступ к файлам",
    "Follow closed": "Контроль закрыт",
    "Follow open": "Контроль открыт",
    "Follow valid.": "Контроль проверен",
    "Follow-up": "Контроль",
    Governance: "Контроль",
    "Gov. open": "Контроль открыт",
    Incidents: "Инциденты",
    "Incident linked": "Инцид. связан",
    "Incident open": "Инцид. открыт",
    Monitor: "Наблюдение",
    Monitored: "Под наблюдением",
    Monitoring: "Наблюдение",
    Observation: "Наблюдение",
    Observed: "Наблюдалось",
    "Open Inc.": "Инцид. открыт",
    "Open evidence": "Подтверждения открыты",
    "Open governance": "Контроль открыт",
    "Open review": "Разбор открыт",
    Outcome: "Результат",
    "Outcome Правила": "Порядок результатов",
    "Outcome policy": "Порядок",
    "Outcome set": "Результаты",
    Outcomes: "Результаты",
    Owner: "Ответственный",
    Policy: "Правила",
    "Patient copy": "Текст пациенту",
    Protocol: "Протокол",
    Ready: "Готово",
    "Real Set": "Рабочие данные",
    "Real ops": "Операции",
    Recheck: "Повтор",
    Recurrence: "Повтор",
    "Recurrence open": "Повтор открыт",
    Register: "Реестр",
    "Release ledger": "Журнал выдачи",
    "Protected set": "Защищённые снимки",
    Render: "Просмотр",
    "Render ready": "Просмотр готов",
    Report: "Отчёт",
    Resolved: "Закрыто",
    Retention: "Срок хранения",
    Review: "Разбор",
    Reviewer: "Проверяющий",
    "Reviewer link": "Связь с разбором",
    "Reviewer linked": "Связано с разбором",
    "Reviewer ops": "Работа проверяющих",
    Reviews: "Проверки",
    Rollback: "Откат",
    "Rollback Run": "Откат проверен",
    "Rollback drills": "Проверки отката",
    "Rollback ready": "Откат готов",
    "SLA": "Срок",
    "Decision log": "Журнал решений",
    Sample: "Выборка",
    Sampled: "Выборка",
    Sampling: "Выборка",
    Second: "Повтор",
    Triage: "Разбор",
    Trend: "Тренд",
    Validation: "Проверка",
    Validated: "Проверено",
    Validators: "Проверяющие",
    Window: "Период",
    Windows: "Периоды",
    Workflow: "Процесс",
    "medical measurement": "измерения",
  };
  if (labels[term]) return labels[term];
  return /[A-Za-z]/.test(term) ? "Показатель" : term;
}

export function humanDisplayValue(value: string): string {
  const labels: Record<string, string> = {
    actionable: "требует действия",
    approved_for_clinical_operations: "готово к работе",
    approved_for_production_analysis: "анализ утверждён",
    approved_for_technical_review: "правила утверждены",
    blocked: "заблокировано",
    draft: "черновик",
    high: "высокий",
    in_review: "на разборе",
    low: "низкий",
    moderate: "средний",
    needs_review: "проверить",
    not_started: "не начато",
    ready: "готово",
    ready_for_clinic_monitoring: "наблюдение готово",
    ready_for_exception_governance: "исключения закрыты",
    ready_for_longitudinal_clinical_validation: "история проверена",
    ready_for_monitored_rollout: "наблюдение готово",
    ready_for_observation_governance: "контроль наблюдения готов",
    ready_for_outcome_governance: "результаты проверены",
    ready_for_post_validation_monitoring: "послепроверка готова",
    ready_for_production_dataset_evidence: "рабочие данные готовы",
    ready_for_production_reviewer_evidence: "подтверждение проверки готово",
    ready_for_production_reviewer_governance: "рабочая проверка готова",
    ready_for_production_rollout: "рабочий запуск готов",
    ready_for_protected_reviewer_evidence: "подтверждение проверки готово",
    ready_for_protected_reviewer_governance: "закрытая проверка готова",
    ready_for_protected_reviewer_validation: "закрытые снимки проверены",
    ready_for_rollout: "запуск готов",
    signed: "подписано",
    technical_ready: "технически готово",
    urgent: "срочно",
  };
  if (labels[value]) return labels[value];
  if (/[А-Яа-яЁё]/.test(value)) return value;
  if (/^\d+(\s*(дн\.|фото))?$/.test(value)) return value;
  if (value.includes("ready")) return "готово";
  if (value.includes("review")) return "на разборе";
  if (value.includes("blocked")) return "заблокировано";
  if (value.includes("approved")) return "утверждено";
  return "служебное значение скрыто";
}
